### ISSUE TITLE
Older python versions?

### ISSUE THREAD

**Issue by KoenWindey** [hilch/Pvi.py#1]
Hi Christoph,

What would it take to make this work on Python 3.4?
I had a quick look and saw extensive use of f-strings, I assume that would have to be adjusted. What else do you think?

I'm hoping to use this on an older Automation PC, running on Windows xp.

Kind regard
Koen

**Comment by hilch** [comment]
Hi Koen,
well this would require to crawl through all the 'What's new' articles in python doc. Had a quick view and found
nothing that could not be done with 3.4 I think. Mainly a wrapper around c_types and a lot of text parsing with regex.
I did not use the async stuff but type annotations somewhere (and f-strings of course).
But WinXP mostly means 32 bit. I used the 64 bit version so the function defs need to be changed as well.

A different approach is to get a newer Python version running on XP.
There is also a question in stackoverflow in regards to this:
https://stackoverflow.com/questions/47516712/what-versions-of-python-will-work-in-windows-xp

But well it is a good idea to reuse old hardware. Why you do not start a fork e.g. 'PviXP.py' :-).
