### ISSUE TITLE
ina2000

### ISSUE THREAD

**Issue by MVTUK** [hilch/Pvi.py#2]
Hi,

how to use INA2000 protocol in python script.

**Comment by hilch** [comment]
well, it starts by using CD='LNINA2' instead of CD='LNANSL'.
But 'Device' parameter are different compared to ANSL.
You have to refer to Automation Studio Online Help or PVI help.
I do not have a sample yet, since INA is outdated.
This project is just a wrapper for PVI. It does not add or remove anything from that.

**Comment by MVTUK** [comment]
ok, but the brwatch ANSL setting value make it as 1 then it is not communication and when i make it as 0 then it was commmunicating with controller. that's why i asking INA2000 protocol. if you have solution for this in python please share.

**Comment by hilch** [comment]
when I started brwatch ANSL did not exist and I used 'CD=LNINA2' as default. Later on they added ANSL and I added this flag to change the 'Line' to 'CD=LNANSL'.
What is the goal ? Why do you have to use INA ?

**Comment by MVTUK** [comment]
with my controller, ANSL doesn't support it. that is why I ask for INA2000 communication. I have read data from the b&r controller using Python. can you please share the LNINA2 sample Python program?

**Comment by hilch** [comment]
which CPU type ?
what kind of device ? Ethernet or Serial ?

**Comment by MVTUK** [comment]
Power panel HMI, Ethernet communication.

**Comment by hilch** [comment]
see simple3.py, please.
all other examples may require even more changes than just the connection settings.

**Comment by MVTUK** [comment]
Thanks for the details. still, I am not getting value from the controller.  I am getting an empty response.

`from time import sleep
from pprint import pprint
from pvi import *

pviConnection = Connection()


line = Line( pviConnection.root, 'LNINA', CD='LNINA2')
device = Device( line, 'TCP', CD='/IF=TcpIp /SA=112' ) 
cpu = Cpu( device, 'PP400', CD='/DAIP=192.168.0.90' )
#cpu = Cpu( device, 'PP400', CD='/DA=32' )


run = True

def cpuErrorChanged( error : int):
    global run

    if error == 0:
        # read content
        allObjects = cpu.externalObjects

        # read module names
        moduleNames = [_['name'] for _ in allObjects if _['type'] == 'Module' ]  

        modules = list()
        for name in moduleNames:  # read the modules' status
            module = Module( cpu, name )
            status = { "Name" : name }
            status.update( module.status )
            modules.append(status)
            module.kill()


        taskNames = [ _['name'] for _ in allObjects if _['type'] == 'Task'] 
        tasks = list()
        for name in taskNames:  # read the tasks' status
            task = Task( cpu, name )
            status = { "Name" : name }
            status.update( task.status )
            tasks.append(status)
            task.kill()


        globalVarnames = [ _['name'] for _ in allObjects if _['type'] == 'Pvar'] 
        globalVariables = list()
        for name in globalVarnames:  # read the variables' status, data type and value
            variable = Variable( cpu, name )
            status = { "Name" : name }
            status.update( variable.status )
            status.update( { "Value" : variable.value} )
            status.update( { "Type" : variable.dataType} )            
            globalVariables.append(status)
            variable.kill()

        with open('PANELPC2100test.txt', 'w') as f:
            f.write("Modules =\n")
            pprint(modules, stream=f, indent = 4)
            f.write("\nTasks =\n")
            pprint(tasks, stream=f, indent = 4)            
            f.write("\nglobalVars =\n")
            pprint(globalVariables, stream=f, indent = 4)  
        print('content.txt was created !')                      
        run = False
    
    elif error:
        raise PviError(error)


cpu.errorChanged = cpuErrorChanged


while run:
    pviConnection.doEvents() # must be cyclically called
    sleep(0.1)`

**Comment by hilch** [comment]
there is just 'PVI-Snapshot' in PVI-Monitor for help.
Try connection with AS first and then have a look into Snapshot.
Then exit AS and PVI-Manager and start the Python script again. Take a Snapshot and compare.
There is not much what I can do from here. I am currently far away from any hardware but the parameters are looking ok.
If you never used PVI-Snapshot I would suggest to contact your local B&R for help.

If there is no solution I will try to address your topic next week.

**Comment by MVTUK** [comment]
ok sure, If possible, please.

**Comment by hilch** [comment]
> I am getting an empty response.

you were right. INA2000 does not support property <Object>.externalObjects. Now an exception will be raised.

Instead I added properties Cpu.tasks, Cpu.variables and Task.variables which do something similar and work with INA.
list_objects4.py, list_objects5.py, list_objects6.py, logger3.py are for you now.

All examples were tested on a real PP65 running AR3.x.
But you will have to use the Python code from repository instead of since V0.4.0 isn't released yet.

**Comment by hilch** [comment]
@MVTUK : any update ? Thanks !

**Comment by MVTUK** [comment]
Hi 

thanks for the code.

I tested with the PP400 controller working fine, thanks.

**Comment by hilch** [comment]
@MVTUK 
thank you for the feedback. I am always happy about a star :-)
I'll close this issue
