### ISSUE TITLE
Refresh Rate (RF) not updating consistently

### ISSUE THREAD

**Issue by KoenWindey** [hilch/Pvi.py#4]
Hi Christoph, 

Happy New Year!

Question: in the simple1.py example, when i change the RF value on the temperature variable, the refresh rate does not always immediately change. Somehow it seems that PVI Manager is remembering the Process Object with its old RF. After running the script a number of times, it eventually updates to the new RF. Also, when I restart PVI Manager, it immediately takes the new RF - obviously because it get created from nothing.

Is this inherent to the behaviour of PVI Manager? Is it because the same Process Object name is used, that it does not get recreated when the script runs again, and instead we just get a new linkID?

Can we somehow avoid this by removing all Process Objects from PVI Manager when the Connection event loop is stopped? I tried to explicitely deInitialise the connection `del(pviConnnection)` at the end of the script, but that made no difference. Perhaps the PviUnlinkAll method? But that's not implemented in Pvi.py I think?

Kind regards,
Koen

**Comment by hilch** [comment]
Happy New Year Koen !

... and you start with so many questions :-)

I always use 'temporary' Objects
(https://help.br-automation.com/#/en/4/automationnet%2Fpvibase%2Fcore%2Fpviobjectprocess.htm)

i.e. the objects are not deleted if another client is still accessing them.
I suppose you are still running Automation Studio accessing these variables in the background ? Use Pvi Snapshot for debugging.
In this case the objects are 'not owned' by your script. Unfortunately I did not add a command to change the refresh rate during runtime. I want to make the things simple (pythonic).

**Comment by KoenWindey** [comment]
Yeah - I'd have to troubleshoot with PVI snapshot to see if something else is keeping the links active. You are right, I typically have Automation Studio as well as a VNC client to the coffee machine open while testing and developing. I haven't verified it outside the testing setup.

It's not a major issue, more something that startled me at first and made me think I misunderstood the use of RF rate.

**Comment by KoenWindey** [comment]
Using snapshot viewer, I can see the links appear when my application starts and shortly after I close it, they are removed.

I think it was mostly a matter of a slight delay in PVI manager removing the links.  Nothing to do with Pvi.py I think.
