### ISSUE TITLE
Variable.valueChanged suggestion

### ISSUE THREAD

**Issue by KoenWindey** [hilch/Pvi.py#7]
Hi Christoph,

The valuechanged callback is very handy if you have a variable that you want to report back at a desired RF rate. And it becomes even better if you have a long list of variables with different RF rates. Each of them will report back at the preset RF rate.

However, the callback function currently only allows for 1 argument, ie. the value itself. It would be good if the callback function could also access the name of the variable. That allows to define the callback function once and use it for multiple variables, each identifying themselves as they return values.

Suggestion for Variable.py therefore:

```
def _eventData( self, wParam, responseInfo ):
    self.__readRawData( wParam, responseInfo )
    if callable(self._valueChanged):
        self._valueChanged(self.name, self._value)
```

This way you can do:
`myVar.valueChanged = lambda name, value: print(f'{name} = {value})`

Kind regards
Koen

**Comment by hilch** [comment]
That's a good idea in principle, but I currently have two concerns:
- Backwards compatibility. Is it actually possible to query how many parameters the callback function expects in the application?
- performance. We then always have to transfer a string, even if this is ignored in many cases. A better way could be to communicate the Variable object itself with the callback.

**Comment by KoenWindey** [comment]
Passing the whole Variable to the callback would even be better I guess. My first reaction was that it would make the performance even worse - but that's without understanding how an Object reference actually is passed in Python... it might actually be quicker than passing a second string as you suggest.

As for backwards compatibility with existing callback functions: I don't think it would help. Any application out there expecting to see a value will need to be adjusted to extract the value from the object.

Perhaps for now a feature branch will do - see how other people may or may not react.

Koen

**Comment by hilch** [comment]
Hi Koen,

please check if this works for you:

2ac7f45791af86f91885fc4596f2367708073bf9

**Comment by KoenWindey** [comment]
This works well, passing the whole object - good idea. Also nice trick for the backward compatibilitiy.

**Comment by hilch** [comment]
Hi @KoenWindey,

unfortunately I had to change the signature of .valueChanged to be consistent with .errorChanged

721f586fd9445a168f62f9238a04fa886ed4654d

Thanks,
Christoph
