### ISSUE TITLE
Unique object names versus object name with path specification

### ISSUE THREAD

**Issue by KoenWindey** [hilch/Pvi.py#8]
Hi Christoph,

I believe throughout, you've chosen to implement object names with path specification. ie: @Pvi/Line/Device/Cpu/Task/Name. With Name being the actual name of the object in the Cpu. However, PVI Manager seems to also allow the use of 'unique object names'. Basically, whatever you want to name an object, as long as it is unique - unrelated to the Name on the Cpu. The CD descriptor of course will hold the Name on the Cpu.

When I follow this approach, I get some funky behaviour. Example:

```
myVar = Variable(parent=Cpu, name=myUniqueName, CD='gHeating.status.actTemp', RF=1000)
print(myVar.name)
```

Result: `@Pvi/Line/Device/Cpu/myUniqueName` 
instead of `@Pvi/Line/Device/Cpu/gHeating.status,actTemp`
or alternatively `myUniqueName`

However, `print(myVar.objectName)`, does give the correct `myUniqueName`.

Obviously `@Pvi/Line/Device/Cpu/myUniqueName` doesn't make much sense - it is not an existing path. 

I guess the issue is this line in the Object class:
`self._name = f'{parentName}{name}'`

My question is: other than possible confusion to users, do you think using 'unique names' could cause any other issues?

Regards
Koen

**Comment by hilch** [comment]
Hi Koen,

yes, I use the hierarchical way for object names. Even with unique names you have to follow the hierarchy principle so I don't see any advantage to use the unique names.

> When I follow this approach, I get some funky behaviour.

yep, that is nonsense. Thank you for reporting.
I think I should assign the content of CD to name in this case.

> My question is: other than possible confusion to users, do you think using 'unique names' could cause any other issues?

yep, could be. I use self._name in many places. I do not see a reason to use both 'name' and 'CD' simultaneously. The application should work with the name of the Variable object instance. Or, what did you expect when using different names in your example ?

**Comment by hilch** [comment]
please check if this fixes the problem

e262919b55b47528cbc454b04c72ef202c901924

**Comment by KoenWindey** [comment]
Hi Christoph,

I don't think the changes quite work the way I was hoping. The master branch basically allows me to define a Variable as follows:
`myVar = Variable(parent=Cpu, name=myUniqueName, CD='gHeating.status.actTemp', RF=1000)`. And that seems perfectly acceptable according to the 'Unique Name' feature, see: [https://help.br-automation.com/#/en/4/automationnet%2Fpvibase%2Fcore%2Fpviobjectuniquename.htm](https://help.br-automation.com/#/en/4/automationnet%2Fpvibase%2Fcore%2Fpviobjectuniquename.htm).

The change you are proposing is basically eliminating this option - whenever the name does not correspond with the name in CD (/RO=xxx), you are replacing it. So you're enforcing the use of object names with path names: [https://help.br-automation.com/#/en/4/automationnet%2Fpvibase%2Fcore%2Fpviobjectpathname.htm](https://help.br-automation.com/#/en/4/automationnet%2Fpvibase%2Fcore%2Fpviobjectpathname.htm).

I guess that's a choice, but it might be best to explain the limitation in the documentation?

Also, you are relying on the use of 'RO=xxx' in the Connection Description. I thought '/RO=xxx' was not strictly needed? Things work fine if use either 'CD=gHeating.status.actTemp' or CD='/RO=gHeating.status.actTemp'.

At the end of the day, I'm not a great fan of the proposed changes, it seems to be adding limitations and I still don't really know why it is needed. Perhaps it is useful if I explain the reason for wanting to use Unique Names.

Let's say I have a long list of Pvars on the PLC - 1000 or so. The program in the PLC has some specific naming format (perhaps it is some shorthand german - and the names end up being quite meaningless to an english-speaking person). Let's say I'm making a datalogger and I want to write the values to a CSV file. For the end user, it would be much more interesting if the name of the variable is readable English.

Now, as input to my little datalogger, I might have a csv file which contains all the variables that are to be logged. I give them the unique 'English' name, I specify the Pvi Path and Object Descriptor. If I can simply use the unique name from the csv file to set up a variable - then it makes it really easy to write the data to the output file, since I have the unique name available in the valueChanged function. And so the valueChanged function can write directly to my output CSV with my unique name.

However, with the changes you are proposing, I have to use a second function, inside the callback function to do a 'look up' of the English unique name against the Pvi Name.

I hope that makes sense. It's definitely solveable from my end with what you are proposing. And if you are adamant that a strict use of the hierarchical naming system is needed - then so be it. As said, it might be worth point this out in the documentation then.

Many thanks
Koen

**Comment by hilch** [comment]
Hi Koen,

ah ok. That means, you need this name just for application internal identification.

what is about this:

If we were now to differentiate between a 'name' and an 'pvi object name' within the object, then we could keep the previous hierarchical naming. 

The disadvantage with unique names is that you have to determine the hierarchy in the CD - string then.
Which means you have to always repeat parts of the path. It's much simpler to derive the hierarchy from the hierarchy of Python objects.

Best Regards,
Christoph

**Comment by hilch** [comment]
Hi @KoenWindey ,

please send your comments about this: 70fa41bcea52f10e314994c4c16e93d3215b7307

`temperature = Variable( task1, name='myTemp', CD = '/RO=gHeating.status.actTemp', RF=2000 )`

there is now a new member 'userName' which holds the 'name':

`print('\n' + temperature.name + ' - ' + temperature.userName)`

on the other hand it is not necessary to use '/RO' in case 'name' points to the right name on plc.

Best Regards,
Christoph

**Comment by hilch** [comment]
completed by 1.2.0
