### ISSUE TITLE
Arrays inside structures not being read when reading the whole variable

### ISSUE THREAD

**Issue by jmauriKB** [hilch/Pvi.py#9]
Hi Christoph,

When reading a variable declared as a structure with arrays inside, the array part is not fully read. Only the first element of the array is returned.

For example, when I try to read a variable of type MC_ENDLESS_STRUCTURE (from library ACP10_MC) I only get the values of the first elements of the array: 
`OrderedDict([('.EndlessPositionData.MTPhase', -1022448), ('.EndlessPositionData.MTDiffInteger', 0), ('.EndlessPositionData.MTDiffFract', 0), ('.EndlessPositionData.RefOffset', -1800000), ('.EndlessPositionData.Checksum', 2966505856)])`

This is the definition of MC_ENDLESS_POSITION:
`MC_ENDLESS_POSITION : 	STRUCT  (*structure to save the endless position*)`
`	EndlessPositionData : ARRAY[0..1] OF MC_ENDLESS_POSITION_DATA;`
`END_STRUCT;`
`MC_ENDLESS_POSITION_DATA : 	STRUCT  (*structure to save the endless position*)`
`	MTPhase : DINT;`
`	MTDiffInteger : DINT;`
`	MTDiffFract : DINT;`
`	RefOffset : DINT;`
`	Checksum : UDINT;`
`END_STRUCT;`

If I try to read directly the array inside the strcture, then it works fine (i.e. gEndlessPosition.EndlessPositionData):
`(OrderedDict([('.MTPhase', -1022448), ('.MTDiffInteger', 0), ('.MTDiffFract', 0), ('.RefOffset', -1800000), ('.Checksum', 2966505856)]), OrderedDict([('.MTPhase', -1022448), ('.MTDiffInteger', 0), ('.MTDiffFract', 0), ('.RefOffset', -1800000), ('.Checksum', 2966505856)]))`

Would it be possible to get the values of all the elements of the array when passing just the name of the variable?

Thank you!

**Comment by hilch** [comment]
Hi Jordi,
thank you for the feedback.
yep, can confirm that.
As any number of complex structures can be thought of here, it will probably take a little longer to solve this issue.

**Comment by hilch** [comment]
Hi @jmauriKB,

can you check if this works for you, please:

7f00c6ea96ac12083ea24585fe34f7c91385fe4b

**Comment by jmauriKB** [comment]
Looks good!

Thank you so much @hilch !
